source 'https://github.com/Cocoapods/Specs.git'

use_frameworks!

platform :ios, '10.0'

target 'FlatAdMoPubAdapter_Example' do
  pod 'FlatAdMoPubAdapter', :path => '../'

  target 'FlatAdMoPubAdapter_Tests' do
    inherit! :search_paths

    
  end
end
